version: '3'
services:
  web:
    image: psschand16/webapp:latest
    ports:
      - '3001:3000'
    environment: 
    - REACT_APP_count=
    - REACT_APP_word=
    - REACT_APP_name=surya1
    - REACT_APP_url=
    - REACT_APP_URL_HOST=${REACT_APP_URL_HOST}
    - REACT_APP_URL_BASEURI=${REACT_APP_URL_BASEURI}
  web2:
    image: psschand16/webapp:latest
    ports:
      - '3002:3000'
    environment: 
    - REACT_APP_count=
    - REACT_APP_word=
    - REACT_APP_name=surya2
    - REACT_APP_url=
    - REACT_APP_URL_HOST=${REACT_APP_URL_HOST}
    - REACT_APP_URL_BASEURI=${REACT_APP_URL_BASEURI}
  web3:
    image: psschand16/webapp:latest
    ports:
      - '3003:3000'
    environment: 
    - REACT_APP_count=
    - REACT_APP_word=
    - REACT_APP_name=surya3
    - REACT_APP_url=
    - REACT_APP_URL_HOST=${REACT_APP_URL_HOST}
    - REACT_APP_URL_BASEURI=${REACT_APP_URL_BASEURI}
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run", "test"]
